### ISSUE TITLE
Unable to generate correct image after requesting an image address[Bug]: 

### ISSUE THREAD

**Issue by wy850813** [bogdanfinn/tls-client#126]
### TLS client version

1.7.6

### System information

window

### Issue description

Unable to generate correct image after requesting an image address

### Steps to reproduce / Code Sample

import tls_client

if __name__ == "__main__":
    client_info = {
        "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "client": "chrome120"}
    session = tls_client.Session(
        client_identifier=client_info["client"],
        random_tls_extension_order=True
    )
    response = session.get("https://aswbe-i.ana.co.jp/rei21c/international_asw/pages/kaptcha.jpg")
    with open("tmp.jpg", "wb") as file:
        file.write(response.content)

**Comment by bogdanfinn** [comment]
Hello @wy850813, we have an example how to download images with the tls client and python here: https://github.com/bogdanfinn/tls-client/blob/master/cffi_dist/example_python/example_image.py

it seems that you are using a third party library which wraps the tls client. you should check that repository and raise an issue there if the bug is really a bug: https://github.com/FlorianREGAZ/Python-Tls-Client

**Comment by wy850813** [comment]
> Hello @wy850813, we have an example how to download images with the tls client and python here: https://github.com/bogdanfinn/tls-client/blob/master/cffi_dist/example_python/example_image.py
> 
> it seems that you are using a third party library which wraps the tls client. you should check that repository and raise an issue there if the bug is really a bug: https://github.com/FlorianREGAZ/Python-Tls-Client

Thank you, it was indeed an issue with the third-party library, and now the images can be successfully downloaded。

**Comment by wy850813** [comment]
thank
