### ISSUE TITLE
Concurrent operation error

### ISSUE THREAD

**Issue by qizhoumeng** [bogdanfinn/tls-client#53]
Running requests under 100 concurrent conditions often results in errors。How to solve it

runtime error: invalid memory address or nil pointer dereference

**Comment by bogdanfinn** [comment]
@qizhoumeng do you maybe have more from the stacktrace? maybe the line number of the file where the nil pointer dereference happens?

**Comment by internpoon** [comment]
happen to me as well. just a little under 100 go routine. sometime even 2-3 concurrent req 

panic: runtime error: invalid memory address or nil pointer dereference

**Comment by bogdanfinn** [comment]
@internpoon do you have maybe more of the stacktrace for me? or even better an example implementation to reproduce the issue?

**Comment by internpoon** [comment]
I just did a very simple request with proxy

<img width="1010" alt="CleanShot 2023-06-16 at 10 23 06@2x" src="https://github.com/bogdanfinn/tls-client/assets/21053694/14151163-5f3a-4744-b2e6-369378649f1f">



<img width="788" alt="CleanShot 2023-06-16 at 10 17 35@2x" src="https://github.com/bogdanfinn/tls-client/assets/21053694/e9393fbd-f5dd-42c3-ace0-72b87ca11f7d">

**Comment by bogdanfinn** [comment]
@internpoon 

First of all the root cause: When setting a proxy on a client instance this creates a complete new underlaying transport struct as we need to connect to the new proxy. In combination with the fact that you are sharing one client instance across multiple go routines this is running into a race condition. What you are by accident doing is changing the proxy for every go routine at once.

You can get around this when you:
a) either synchronize the proxy setting across all go routines which are sharing the same client and make sure no go routine is doing something with the transport while its being recreated due to the proxy switch 
b) or you create a separate client per go routine.


Next to it you should read about using the defer statement inside a for loop.

This might also be related to #44 because it seems like there the same thing is done with proxies and sessions.
